use bdbibliacatolica;

-- Cadastro do Idioma Português - Brasil
insert into idioma (NomeIdioma) values ("Português - Brasil");


-- Cadastro da tradução CNBB
insert into traducoes (NomeTraducao, ObservacaoTraducao, AnoTraducao, IdIdioma) values ("Tradução - CNBB", "Tradução segundo a Conferência Nacional dos Bispos do Brasil, consultada em 2025.", "2025-01-28", 1);


-- Cadastro das classes dos livros
insert into classeslivros (NomeClasse, DescricaoClasse) values 
("Antigo Testamento", "As Escrituras Hebraicas, conhecidas pelos cristãos como Antigo ou Velho Testamento, têm 46 livros,"),

("Novo Testamento", "Novo Testamento, também chamado de Nova Aliança, é a coleção de livros que compõe a segunda parte da Bíblia cristã."),

("Pentateuco", "O Pentateuco corresponde aos cinco primeiros livros do Antigo Testamento."),

("Livros Históricos", "Mais do que história propriamente dita, esses livros são narrativas. Sua intenção é apresentar modelos particulares de vivência e aplicação da fé dentro de situações difíceis, principalmente as enfrentadas pelos judeus fora de sua terra."),

("Sapienciais", "Os livros poéticos ou sapienciais, foram escritos, em sua maioria, em linguagem poética, fazendo uso de metáforas, e têm um caráter de ensinamento para alcançar a sabedoria."),

("Profetas", 'Os livros proféticos são compostos por profecias, que são mensagens de homens com fé profunda que procuram levar as pessoas a um relacionamento com Deus.'),

("Evangelhos", "Os evangelhos são os primeiros livros do Novo Testamento da Bíblia. Os evangelhos foram escritos para preservar os ensinamentos de Jesus e revelar aspectos da natureza de Deus. Eles não são biografias de Jesus, mas sim explicações teológicas dos eventos da sua vida."),

("Cartas", "As cartas da Bíblia são chamadas de epístolas e fazem parte do Novo Testamento. Elas são comunicações pessoais e específicas, escritas em formato de correspondência.");


-- Cadatro dos Autores dos Livros
insert into autoreslivros (NomeAutor) values
("Moisés"),
("Josué e possíveis sacerdotes"),
("Samuel"),
("Natã"),
("Gade"),
("Possivelmente Jeremias ou outros Profetas"),
("Esdras"),
("Neemias"),
("Autor desconhecido"),
("Mardoqueu"),
("Autor desconhecido (talvez Moisés ou Salomão)"),
("Davi, Asafe, filhos de Corá e outros"),
("Salomão"),
("Agur"),
("Lemuel"),
("Autor desconhecido (talvez Salomão)"),
("Jesus, filho de Sirac"),
("Isaías"),
("Jeremias"),
("Baruc"),
("Ezequiel"),
("Daniel"),
("Oseias"),
("Joel"),
("Amós"),
("Obadias"),
("Jonas"),
("Miqueias"),
("Naum"),
("Habacuque"),
("Sofonias"),
("Ageu"),
("Zacarias"),
("Malaquias"),
("Apóstolo Mateus"),
("João Marcos (companheiro de Pedro)"),
("Lucas (companheiro de Paulo)"),
("Apóstolo João"),
("Paulo"),
("Autoria incerta (possívelmente Paulo ou um de seus dicípulos)"),
("Tiago (parente de Jesus)"),
("Apóstolo Pedro"),
("Judas Tadeu (apóstolo)");


-- Cadastro dos Livros
insert into livros (NumeroOrdem, NomeLivro, AbreviacaoLivro, IdAutor, IdTraducao) values
("Gênesis", "Gn", 1),
("Êxodo", "Ex", 1),
("Levítico", "Lv", 1),
("Números", "Nm", 1),
("Deuteronômio", "Dt", 1),

("Josué", "Js", 2),
("Juízes", "Jz", 3),
("Rute", "Rt", 3),
("1 Samuel", "1Sm", 4),
("2 Samuel", "2Sm", 5),
("1 Reis", "1Rs", 6),
("2 Reis", "2Rs", 6),
("1 Crônicas", "1Cr", 7),
("2 Crônicas", "2Cr", 7),
("Esdras", "Esd", 7),
("Neemias", "Ne", 8),
("Tobias", "Tb", 9),
("Judite", "Jt", 9),
("Ester", "Est", 10),
("1 Macabeus", "1Mc", 9),
("2 Macabeus", "2Mc", 9),

("Jó", "Jó", 11),
("Salmos", "Sl", 12),
("Provérbios", "Pr", 14),
("Eclesiastes", "Ecl", 13),
("Cântico dos Cânticos", "Ct", 13),
("Sabedoria", "Sb", 16),
("Eclesiástico", "Eclo", 17),
("Isaías", "Is", 18),
("Jeremias", "Jr", 19),
("Lamentações", "Lm", 19),
("Baruc", "Br", 20),
("Ezequiel", "Ez", 21),
("Daniel", "Dn", 22),
("Oseias", "Os", 23),
("Joel", "Jl", 24),
("Amós", "Am", 25),
("Obadias", "Ob", 26),
("Jonas", "Jn", 27),
("Miqueias", "Mq", 28),
("Naum", "Na", 29),
("Habacuque", "Hab", 30),
("Sofonias", "Sf", 31),
("Ageu", "Ag", 32),
("Zacarias", "Zc", 33),
("Malaquias", "Ml", 34),

("Mateus", "Mt", 35),
("Marcos", "Mc", 36),
("Lucas", "Lc", 37),
("João", "Jo", 38),
("Atos dos Apóstolos", "At", 37),

("Romanos", "Rm", 39),
("1 Coríntios", "1Cor", 39),
("2 Coríntios", "2Cor", 39),
("Gálatas", "Gl", 39),
("Efésios", "Ef", 39),
("Filipenses", "Fl", 39),
("Colossenses ", "Cl", 39),
("1 Tessalonicenses", "1Ts", 39),
("2 Tessalonicenses", "2Ts", 39),
("1 Timóteo", "1Tm", 39),
("2 Timóteo", "2Tm", 39),
("Tito", "Tt", 39),
("Filemon ", "Fm", 39),

("Hebreus", "Hb", 40),
("Tiago", "Tg", 41),
("1 Pedro", "1Pd", 42),
("2 Pedro", "2Pd", 42),
("1 João", "1Jo", 38),
("2 João", "2Jo", 38),
("3 João", "3Jo", 38),
("Judas", "Jd", 43),
("Apocalipse", "Ap", 38);


-- Linkar Classes com os Livros
insert into livrosclasses (IdLivro, IdClasse) values
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),

(1, 3),
(2, 3),
(3, 3),
(4, 3),
(5, 3),

(6, 1),
(7, 1),
(8, 1),
(9, 1),
(10, 1),
(11, 1),
(12, 1),
(13, 1),
(14, 1),
(15, 1),
(16, 1),
(17, 1),
(18, 1),
(19, 1),
(20, 1),
(21, 1),

(6, 4),
(7, 4),
(8, 4),
(9, 4),
(10, 4),
(11, 4),
(12, 4),
(13, 4),
(14, 4),
(15, 4),
(16, 4),
(17, 4),
(18, 4),
(19, 4),
(20, 4),
(21, 4),

(22, 1),
(23, 1),
(24, 1),
(25, 1),
(26, 1),
(27, 1),
(28, 1),
(29, 1),
(30, 1),
(31, 1),
(32, 1),
(33, 1),
(34, 1),
(35, 1),
(36, 1),
(37, 1),
(38, 1),
(39, 1),
(40, 1),
(41, 1),
(42, 1),
(43, 1),
(44, 1),
(45, 1),
(46, 1),

(22, 5),
(23, 5),
(24, 5),
(25, 5),
(26, 5),
(27, 5),
(28, 5),

(29, 6),
(30, 6),
(31, 6),
(32, 6),
(33, 6),
(34, 6),
(35, 6),
(36, 6),
(37, 6),
(38, 6),
(39, 6),
(40, 6),
(41, 6),
(42, 6),
(43, 6),
(44, 6),
(45, 6),
(46, 6),

(47, 2),
(48, 2),
(49, 2),
(50, 2),
(51, 2),

(47, 7),
(48, 7),
(49, 7),
(50, 7),

(52, 2),
(53, 2),
(54, 2),
(55, 2),
(56, 2),
(57, 2),
(58, 2),
(59, 2),
(60, 2),
(61, 2),
(62, 2),
(63, 2),
(64, 2),
(65, 2),
(66, 2),
(67, 2),
(68, 2),
(69, 2),
(70, 2),
(71, 2),
(72, 2),
(73, 2),

(52, 8),
(53, 8),
(54, 8),
(55, 8),
(56, 8),
(57, 8),
(58, 8),
(59, 8),
(60, 8),
(61, 8),
(62, 8),
(63, 8),
(64, 8),
(65, 8),
(66, 8),
(67, 8),
(68, 8),
(69, 8),
(70, 8),
(71, 8),
(72, 8);